/// <reference lib="webworker" />
import { WasmCallbacks, createBrowserCallbacks } from "./wasmCallbacks";

// This file is the entry point for the WASM worker in browser context.
// It loads the WASM module and communicates with the main extension via postMessage.

declare function acquireVsCodeApi(): {
  postMessage(message: unknown): void;
  getState(): unknown;
  setState(state: unknown): void;
};

interface WasmModule {
  lsp_init(): number;
  lsp_process_message(ptr: number): number;
  lsp_push_message(ptr: number): void;
  lsp_get_response(): number;
  lsp_shutdown(): void;
  lsp_register_callbacks(
    readFile: number,
    fileExists: number,
    isFile: number,
    isDirectory: number,
    dirList: number,
    getCurrentDirectory: number,
    httpFetch: number,
    command: number,
  ): void;
  _malloc(size: number): number;
  _free(ptr: number): void;
  UTF8ToString(ptr: number): string;
  stringToUTF8(str: string, ptr: number, maxBytes: number): void;
  ccall(
    ident: string,
    returnType: string | null,
    argTypes: string[],
    args: unknown[],
  ): unknown;
}

let wasmModule: WasmModule | null = null;
let callbacks: WasmCallbacks | null = null;

function allocateString(str: string): number {
  if (!wasmModule) return 0;
  const len = str.length * 3 + 1; // UTF-8 max 3 bytes per char
  const ptr = wasmModule._malloc(len);
  wasmModule.stringToUTF8(str, ptr, len);
  return ptr;
}

function readString(ptr: number): string {
  if (!wasmModule || ptr === 0) return "";
  return wasmModule.UTF8ToString(ptr);
}

async function initWasm(): Promise<boolean> {
  try {
    // Import the WASM module (generated by Emscripten)
    // @ts-ignore - bin/server.js is a build artifact produced by Emscripten
    const moduleLoader = await import("../bin/server.js");
    wasmModule = (await moduleLoader.default()) as unknown as WasmModule;

    callbacks = createBrowserCallbacks();

    // Register callbacks with the WASM module
    if (wasmModule && typeof wasmModule.ccall === "function") {
      // TODO: Properly wrap JS callbacks as C function pointers using addFunction
      wasmModule.ccall("lsp_register_callbacks", null, [], []);
    }

    // Initialize the LSP server
    const result = wasmModule!.lsp_init();
    return result === 0;
  } catch (error) {
    console.error("Failed to initialize WASM module:", error);
    return false;
  }
}

function processMessage(message: string): string {
  if (!wasmModule) return "";

  const msgPtr = allocateString(message);
  const responsePtr = wasmModule.lsp_process_message(msgPtr);
  const response = readString(responsePtr);

  wasmModule._free(msgPtr);
  if (responsePtr !== 0) {
    wasmModule._free(responsePtr);
  }

  return response;
}

// Handle messages from the main extension
self.onmessage = async (event: MessageEvent) => {
  const { type, id, message } = event.data;

  switch (type) {
    case "init": {
      const success = await initWasm();
      self.postMessage({ type: "init-result", success });
      break;
    }
    case "message": {
      if (!wasmModule) {
        self.postMessage({
          type: "error",
          id,
          error: "WASM module not initialized",
        });
        break;
      }
      try {
        const response = processMessage(message);
        self.postMessage({ type: "response", id, message: response });
      } catch (error) {
        self.postMessage({ type: "error", id, error: String(error) });
      }
      break;
    }
    case "shutdown": {
      if (wasmModule) {
        wasmModule.lsp_shutdown();
      }
      self.postMessage({ type: "shutdown-result" });
      break;
    }
    case "callback-response": {
      // Handle async callback responses from the main thread
      // This is used for file reads, HTTP fetches, etc.
      break;
    }
  }
};
